Repository NationalGenomicsInfrastructure/ngi_reports, pull requests merged in 2024-09, with the labels that each got.

#164 Try fixing the extra empty line between fcs in html report
  VERSIONLOG.md
  data/report_templates/project_summary.md
  ngi_reports/reports/project_summary.py
Labels: no validation

#161 check correct dir when generating reports
  ngi_reports/ngi_reports.py
  ngi_reports/reports/project_summary.py
Labels: enhancement, no validation

#165 Fix issue with empty owner under order_details
  VERSIONLOG.md
  ngi_reports/utils/entities.py
Labels: bug, no validation
